config/routes.rb
  Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    root "pages#index"

    resources :brands 
    resources :nails
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :nails, dependent: :destroy

    validates :name, presence: true
end

app/models/nail.rb
class Nail < ApplicationRecord
  belongs_to :brand

  validates :brand_id, presence: true
  validates :code, presence: true
  validates :color, presence: true
  validates :amount, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.create(brand_params)

    if @brand.save
      redirect_to brands_path
    else
      render :new, status: :unprocessable_identity
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to brands_path
    else
      render :edit, status: :unprocessable_identity
    end
  end

  def destroy
    @brand = Brand.find(params[:id])

    @brand.destroy

    redirect_to brands_path, status: :see_other
  end

  private
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/nails_controller.rb
class NailsController < ApplicationController
  def index
    @nails = Nail.all
  end

  def new
    @brands = Brand.all
    @nail = Nail.new
  end
  
  def edit
    @nail = Nail.find(params[:id])
  end

  def update
    @nail = Nail.find(params[:id])

    if @nail.update(nail_params)
      redirect_to nails_path
    else
      render :edit, status: :unprocessable_identity
    end
  end

  def create
    @brands = Brand.all
    @nail = Nail.create(nail_params)

    if @nail.save
      redirect_to nails_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @nail = Nail.find(params[:id])

    @nail.destroy

    redirect_to nails_path, status: :see_other
  end

  private
    def nail_params
      params.require(:nail).permit(:brand_id, :code, :color, :amount)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/nails_helper.rb
module NailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">NailStash</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Nails", nails_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Brands", brands_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/brands/_form.html.erb
<%= form_with model: brand do |form|%>
    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name %>
        <% brand.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <%= form.submit %>
<% end %>

app/views/brands/edit.html.erb
<h1>Edit a brand</h1>

<%= render "form", brand: @brand %>

app/views/brands/index.html.erb
<h1>Brands</h1>

<div class="container" style="width: 100%;">
    <div class="row">
        <div class="col-11">
            <table class="table" style="width: 100%;">
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Actions</th>
                </thead>
                <tbody>
                    <% @brands.each do |brand|%>
                    <tr>
                        <th scope="row"><%= brand.id %></th>
                        <td><%= brand.name %></td>
                        <td><%= brand.nails.count %></td>
                        <td>
                            <%= button_to "Info", brand_path(brand), method: "get", :form => { :style => "display: inline"}, :class => "btn btn-primary"%>
                            <%= button_to "Edit", edit_brand_path(brand), method: "get", :form => { :style => "display: inline"}, :class => "btn btn-success" %>
                            <%= button_to "Delete", brand_path(brand), method: "delete", :form => { :style => "display: inline"}, :class => "btn btn-danger", data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                            }%>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-1">
            <%= button_to "Create", new_brand_path, method: "get", :form => { :style => "display: inline"}, :class => "btn btn-primary"%>
        </div>
    </div>
</div>

<!-- 
<div class="container">
    <div class="row">
        <div class="col-9">
            <table class="table" style="width: 100%;">
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Delete</th>
                    <th scope="col">Name</th>
                </thead>
                <tbody>
                    <% @brands.each do |brand| %>
                        <tr>
                            <th scope="row"><%= brand.id %></th>
                            <td><%= brand.name %></td>
                            <td><%= brand.nails.count %></td>
                            <td>Update</td>
                            <td>Delete</td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-3">

        </div>
    </div>
</div>
-->
<!--
<div class="container" style="width: 100%;">
    <table class="table" style="width: 100%;">
        <thead>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Actions</th>
        </thead>
        <tbody>
            <% @brands.each do |brand| %>
                <tr>
                    <th scope="row"><%= brand.id %></th>
                    <td><%= brand.name %></td>
                    <td><%= brand.nails.count %></td>
                    <td>
                        <button type="button" class="btn btn-primary"><box-icon name='show'></box-icon></button>
                        <button type="button" class="btn btn-success"><box-icon name='edit'></box-icon></button>
                        <button type="button" class="btn btn-danger"><box-icon name='trash'></box-icon></button>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

-->

app/views/brands/new.html.erb
<h1>Create new brand</h1>

<%= render "form", brand: @brand %>

app/views/brands/show.html.erb
<h1><%= @brand.name %></h1>

<div class="container" style="width: 100%;">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NailStash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
  </head>

  <body>
    <%= render "navbar" %>

    <%= yield %>
  </body>
</html>

app/views/nails/_form.html.erb
<%= form_with model: @nail do |form|%>
    <div class="form-group">
        <%= form.label :brand_id %>
        <%= form.collection_select :brand_id, Brand.all, :id, :name, prompt: true %>
    </div>
    <div class="form-group">
        <%= form.label :code %>
        <%= form.number_field :code %>
        <% @nail.errors.full_messages_for(:code).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="form-group">
        <%= form.label :color %>
        <%= form.text_field :color %>
        <% @nail.errors.full_messages_for(:color).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="form-group">
        <%= form.label :amount %>
        <%= form.number_field :amount %>
        <% @nail.errors.full_messages_for(:amount).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <%= form.submit %>
<% end %>

app/views/nails/_nail.html.erb
 <tr>
    <th scope="row"><%= nail.id %></th>
    <td><%= nail.brand.name %></td>
    <td><%= nail.code %></td>
    <td><%= nail.color %></td>
    <td><%= nail.amount %></td>
    <td>
        <%= button_to "Info", nail_path(nail), method: "get", :form => { :style => "display: inline"}, :class => "btn btn-primary"%>
        <%= button_to "Edit", nail_path(nail), method: "get", :form => { :style => "display: inline"}, :class => "btn btn-success" %>
        <%= button_to "Delete", nail_path(nail), method: "delete", :form => { :style => "display: inline"}, :class => "btn btn-danger", data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        }%>
    </td>
</tr>

app/views/nails/edit.html.erb
<h1>Edit nail: <%= @nail.code %></h1>

<%= render "form", nail: @nail %>

app/views/nails/index.html.erb
<h1>Nails</h1>

<div class="container" style="width: 100%;">
    <div class="row">
        <div class="col-11">
            <table class="table" style="width: 100%;">
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Code</th>
                    <th scope="col">Color</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Actions</th>
                </thead>
                <tbody>
                    <% @nails.each do |nail|%>
                    <tr>
                        <th scope="row"><%= nail.id %></th>
                        <td><%= nail.brand.name %></td>
                        <td><%= nail.code %></td>
                        <td><%= nail.color %></td>
                        <td><%= nail.amount %></td>
                        <td>
                            <%= button_to "Edit", edit_nail_path(nail), method: "get", :form => { :style => "display: inline"}, :class => "btn btn-success" %>
                            <%= button_to "Delete", nail_path(nail), method: "delete", :form => { :style => "display: inline"}, :class => "btn btn-danger", data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                            }%>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-1">
            <%= button_to "Create", new_nail_path, method: "get", :form => { :style => "display: inline"}, :class => "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/nails/new.html.erb
<h1>Create new nail</h1>

<%= render "form" %>

app/views/pages/index.html.erb
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">NailStash</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">A way to store all the nail polish. Built with Ruby on Rails and Bootstrap</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Brand</button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Nails</button>
      </div>
    </div>
</div>